spring:
    redis:
        host: 47.106.214.38
        port: 6379
        password:
        database: 0
        pool:
              max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
              max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-idle: 8 # 连接池中的最大空闲连接
              min-idle: 0 # 连接池中的最小空闲连接